const products=[
 {id:'c1',cat:'candles',name:'Хвойный лес',latin:'Pinus sylvestris',size:'180 г',price:1690,img:'assets/hero.png',desc:'Хвоя, смола и влажный мох. Тихий древесный аромат леса.'},
 {id:'c2',cat:'candles',name:'Облепиха',latin:'Hippophae rhamnoides',size:'180 г',price:1690,img:'assets/hero.png',desc:'Кислая ягода, зелёные листья и сухая древесина.'},
 {id:'c3',cat:'candles',name:'Лайм & базилик',latin:'Ocimum × Citrus',size:'180 г',price:1690,img:'assets/hero.png',desc:'Свежий лайм и зелёный базилик с прохладным травяным оттенком.'},
 {id:'c4',cat:'candles',name:'Сандал',latin:'Santalum album',size:'180 г',price:1690,img:'assets/hero.png',desc:'Мягкая сухая древесина, специи и тёплая смолистость.'},
 {id:'c5',cat:'candles',name:'Полынь',latin:'Artemisia absinthium',size:'180 г',price:1690,img:'assets/hero.png',desc:'Сухая горькая зелень, травы и древесные ноты.'},
 {id:'d1',cat:'diffusers',name:'Облепиха',latin:'Hippophae rhamnoides',size:'100 мл',price:1790,img:'assets/hero.png',desc:'Кислая ягода, зелёные листья и сухая древесина.'},
 {id:'d2',cat:'diffusers',name:'Лайм & базилик',latin:'Ocimum × Citrus',size:'100 мл',price:1790,img:'assets/hero.png',desc:'Свежий лайм и зелёный базилик.'},
 {id:'d3',cat:'diffusers',name:'Сандал',latin:'Santalum album',size:'100 мл',price:1790,img:'assets/hero.png',desc:'Мягкая сухая древесина и специи.'},
 {id:'d4',cat:'diffusers',name:'Хвойный лес',latin:'Pinus sylvestris',size:'100 мл',price:1790,img:'assets/hero.png',desc:'Хвоя, смола и влажный мох.'},
 {id:'a1',cat:'car',name:'Облепиха',latin:'Hippophae rhamnoides',size:'8 мл',price:1290,img:'assets/hero.png',desc:'Стеклянный флакон-куб с деревянной крышкой.'},
 {id:'a2',cat:'car',name:'Лайм & базилик',latin:'Ocimum × Citrus',size:'8 мл',price:1290,img:'assets/hero.png',desc:'Стеклянный флакон-куб с деревянной крышкой.'},
 {id:'a3',cat:'car',name:'Сандал',latin:'Santalum album',size:'8 мл',price:1290,img:'assets/hero.png',desc:'Стеклянный флакон-куб с деревянной крышкой.'},
 {id:'a4',cat:'car',name:'Хвойный лес',latin:'Pinus sylvestris',size:'8 мл',price:1290,img:'assets/hero.png',desc:'Стеклянный флакон-куб с деревянной крышкой.'},
 {id:'s1',cat:'sachets',name:'Лаванда',latin:'Lavandula angustifolia',size:'30 г',price:990,img:'assets/hero.png',desc:'Восковое саше с сухоцветами.'},
 {id:'s2',cat:'sachets',name:'Розмарин',latin:'Rosmarinus officinalis',size:'30 г',price:990,img:'assets/hero.png',desc:'Восковое саше с ботаническими нотами.'},
 {id:'s3',cat:'sachets',name:'Жасмин',latin:'Jasminum officinale',size:'30 г',price:990,img:'assets/hero.png',desc:'Цветочный аромат в восковой форме.'},
 {id:'s4',cat:'sachets',name:'Сандал',latin:'Santalum album',size:'30 г',price:990,img:'assets/hero.png',desc:'Тёплая древесная композиция.'},
 {id:'s5',cat:'sachets',name:'Полынь',latin:'Artemisia absinthium',size:'30 г',price:990,img:'assets/hero.png',desc:'Сухая зелень и травянистая горечь.'}
];
let cart=JSON.parse(localStorage.getItem('svoyaCart')||'[]');
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function renderGrid(cat,id){document.getElementById(id).innerHTML=products.filter(p=>p.cat===cat).map(p=>`<article class="product-card" data-id="${p.id}"><div class="product-photo"><img src="${p.img}" alt="${p.name}"></div><div class="product-name">${p.name}</div><div class="product-latin">${p.latin}</div><div class="product-meta"><span>${p.size}</span><strong class="product-price">${money(p.price)}</strong></div></article>`).join('')}
renderGrid('candles','candlesGrid');renderGrid('diffusers','diffusersGrid');renderGrid('car','carGrid');renderGrid('sachets','sachetsGrid');
function save(){localStorage.setItem('svoyaCart',JSON.stringify(cart));updateCart()}
function updateCart(){document.getElementById('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);document.getElementById('cartItems').innerHTML=cart.length?cart.map(x=>{const p=products.find(p=>p.id===x.id);return `<div class="cart-row"><img class="cart-thumb" src="${p.img}" alt=""><div><strong>${p.name}</strong><small>${p.size} · ${money(p.price)}</small><div class="qty"><button data-minus="${p.id}">−</button><span>${x.qty}</span><button data-plus="${p.id}">+</button></div></div><button class="remove" data-remove="${p.id}">×</button></div>`}).join(''):'<p style="color:var(--muted);padding:25px 0">Корзина пока пуста.</p>';document.getElementById('cartTotal').textContent=money(cart.reduce((a,x)=>a+products.find(p=>p.id===x.id).price*x.qty,0))}
updateCart();
function openDrawer(){document.getElementById('cartDrawer').classList.add('open');document.getElementById('backdrop').classList.add('open')};function closeDrawer(){document.getElementById('cartDrawer').classList.remove('open');document.getElementById('backdrop').classList.remove('open')}
document.getElementById('openCart').onclick=openDrawer;document.getElementById('closeCart').onclick=closeDrawer;document.getElementById('backdrop').onclick=closeDrawer;
document.addEventListener('click',e=>{const card=e.target.closest('.product-card');if(card){const p=products.find(x=>x.id===card.dataset.id);openProduct(p)}if(e.target.dataset.plus)addQty(e.target.dataset.plus,1);if(e.target.dataset.minus)addQty(e.target.dataset.minus,-1);if(e.target.dataset.remove)removeItem(e.target.dataset.remove);if(e.target.dataset.close)document.getElementById(e.target.dataset.close).classList.remove('open')});
function addQty(id,n){const x=cart.find(x=>x.id===id);if(x)x.qty+=n;if(x&&x.qty<=0)cart=cart.filter(x=>x.id!==id);save()};function removeItem(id){cart=cart.filter(x=>x.id!==id);save()};function add(id){const x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({id,qty:1});save()}
let currentProduct=null;function openProduct(p){currentProduct=p;document.getElementById('modalImage').src=p.img;document.getElementById('modalImage').alt=p.name;document.getElementById('modalLatin').textContent=p.latin;document.getElementById('modalName').textContent=p.name;document.getElementById('modalDesc').textContent=p.desc;document.getElementById('modalSize').textContent=p.size;document.getElementById('modalPrice').textContent=money(p.price);document.getElementById('productModal').classList.add('open')};document.getElementById('modalAdd').onclick=()=>{add(currentProduct.id);document.getElementById('productModal').classList.remove('open');openDrawer()};
document.getElementById('checkoutBtn').onclick=()=>{if(!cart.length){alert('Добавьте товар в корзину.');return}document.getElementById('checkoutSummary').innerHTML=cart.map(x=>{const p=products.find(p=>p.id===x.id);return `<div class="summary-line"><span>${p.name} × ${x.qty}</span><strong>${money(p.price*x.qty)}</strong></div>`}).join('')+`<div class="summary-line"><strong>Итого</strong><strong>${document.getElementById('cartTotal').textContent}</strong></div>`;document.getElementById('checkoutModal').classList.add('open');closeDrawer()};
document.getElementById('orderForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);const lines=cart.map(x=>{const p=products.find(p=>p.id===x.id);return `${p.name} — ${p.size} × ${x.qty} — ${money(p.price*x.qty)}`}).join('\n');const text=`ЗАКАЗ «СВОЯ АТМОСФЕРА»\n\n${lines}\n\nИтого: ${document.getElementById('cartTotal').textContent}\n\nИмя: ${fd.get('name')}\nКонтакт: ${fd.get('contact')}\nКомментарий: ${fd.get('comment')||'—'}`;navigator.clipboard?.writeText(text);const result=document.getElementById('orderResult');result.hidden=false;result.innerHTML=`Заказ сформирован и скопирован в буфер обмена. Сейчас это демо-режим: вставьте текст в удобный канал связи с клиентом.<br><button type="button" id="copyAgain">Скопировать заказ ещё раз</button>`;document.getElementById('copyAgain').onclick=()=>navigator.clipboard?.writeText(text)};
